NAME = slider-am
APP = /home/zhanghaonan/ics2019/nexus-am/apps/slider/build/slider-x86-navy
OBJS = /home/zhanghaonan/ics2019/nexus-am/apps/slider/build/x86-navy//main.o /home/zhanghaonan/ics2019/nexus-am/apps/slider/build/x86-navy//image.o /home/zhanghaonan/ics2019/nexus-am/am/build/am-x86-navy.a /home/zhanghaonan/ics2019/nexus-am/libs/klib/build/klib-x86-navy.a
LIBS += libndl
include /home/zhanghaonan/ics2019/navy-apps/Makefile.app
